'\" t
.\"     Title: mariebuild
.\"    Author: Marie Eckert
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2025-03-12
.\"    Manual: MARIEBUILD
.\"    Source: MARIEBUILD
.\"  Language: English
.\"
.TH "MARIEBUILD" "1" "2025-03-12" "MARIEBUILD" "MARIEBUILD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
mariebuild \- A build system primarly designed and intended for my use.
.SH "SYNPOSIS"
.sp
\fBmb\fP [OPTIONS...]
.SH "OPTIONS"
.sp
\fB\-f, \-\-force\fP
.RS 4
Force fulfillment of incremental c_rules.
.RE
.sp
\fB\-i <file>, \-\-in=<file>\fP
.RS 4
Specify a build file.
.RE
.sp
\fB\-k, \-\-keep\-going\fP
.RS 4
Ignore any failures/errors (if possible) and keep on building.
.RE
.sp
\fB\-n, \-\-no\-splash\fP
.RS 4
Disable splash screen/logo.
.RE
.sp
\fB\-t <target>, \-\-target=<target>\fP
.RS 4
Specify the build target.
.RE
.sp
\fB\-v <level>, \-\-verbosity=<level>\fP
.RS 4
Set the verbosity level (0\-3).
.RE
.sp
\fB\-?, \-\-help\fP
.RS 4
Give a help list.
.RE
.sp
\fB\-\-usage\fP
.RS 4
Give a short usage message.
.RE
.sp
\fB\-V, \-\-version\fP
.RS 4
Print program version.
.RE
.SH "COPYING"
.sp
Copyright (c) 2024, Marie Eckert.
.br
This software is licensed under the BSD 3\-Clause license.
.SH "AUTHOR"
.sp
Marie Eckert